import numpy as np
import time
import matplotlib.pyplot as plt
from keras.utils import np_utils
from keras.layers import concatenate
SSH_train = np.expand_dims(np.load('F:/eddy_data/data_eddynet/trainAVISO-SSH_2000-2010.npy'),3)[:,25:168+25,280-200:,:]
Seg_train = np.expand_dims(np.load('F:/eddy_data/data_eddynet/trainSegmentation_2000-2010.npy'),3)[:,25:168+25,280-200:,:]
Seg_train_categor = np_utils.to_categorical(np.reshape(Seg_train[:,:,:,0],(4018, -1, 4)), 3)
#a = np.reshape(Seg_train, (4018, -1, 8))
#Seg_train_categor1 = np_utils.to_categorical(np.reshape(Seg_train, (4018, -1, 8)), 3)
#print(len(SSH_train))
#print(a.shape)
#print(Seg_train_categor)
#print(Seg_train_categor.shape)
time1 = time.time()
randindex = np.random.randint(2,len(SSH_train)-2)
plt.figure(figsize=(20,10))
plt.subplot(151)
plt.imshow(SSH_train[randindex-2,:,:,0], cmap='viridis')
#plt.colorbar(extend='both', fraction=0.042, pad=0.04)
plt.axis('off')
#plt.title('SSH', fontsize=24)
plt.subplot(152)
plt.imshow(SSH_train[randindex-1,:,:,0], cmap='viridis')
#plt.colorbar(extend='both', fraction=0.042, pad=0.04)
plt.axis('off')
#plt.title('SSH', fontsize=24)
plt.subplot(153)
plt.imshow(SSH_train[randindex,:,:,0], cmap='viridis')
#plt.colorbar(extend='both', fraction=0.042, pad=0.04)
plt.axis('off')
#plt.title('SSH', fontsize=24)
plt.subplot(154)
plt.imshow(SSH_train[randindex+1,:,:,0], cmap='viridis')
#plt.colorbar(extend='both', fraction=0.042, pad=0.04)
plt.axis('off')
#plt.title('SSH', fontsize=24)
plt.subplot(155)
plt.imshow(SSH_train[randindex+2,:,:,0], cmap='viridis')
#plt.show()
time2 = time.time()
print(time2-time1)
'''
randindex = np.random.randint(0,len(SSH_train)-3)
plt.figure(figsize=(20,10))
plt.subplot(141)
plt.imshow(Seg_train[randindex,:,:,0], cmap='viridis')
#plt.colorbar(extend='both', fraction=0.042, pad=0.04)
plt.axis('off')
#plt.title('groundtruth Segmentation', fontsize=24)
plt.subplot(142)
plt.imshow(Seg_train[randindex+1,:,:,0], cmap='viridis')
#plt.colorbar(extend='both', fraction=0.042, pad=0.04)
plt.axis('off')
#plt.title('groundtruth Segmentation', fontsize=24)
plt.subplot(143)
plt.imshow(Seg_train[randindex+2,:,:,0], cmap='viridis')
#plt.colorbar(extend='both', fraction=0.042, pad=0.04)
plt.axis('off')
#plt.title('groundtruth Segmentation', fontsize=24)
plt.subplot(144)
plt.imshow(Seg_train[randindex+3,:,:,0], cmap='viridis')
#plt.colorbar(extend='both', fraction=0.042, pad=0.04)
plt.axis('off')
#plt.title('groundtruth Segmentation', fontsize=24)
plt.show()
'''
